# Generated by Django 5.2.4 on 2025-11-08 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('role', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('date_doc', models.DateField(blank=True, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('titre', models.TextField(blank=True, null=True)),
                ('extra_keyword', models.JSONField(blank=True, null=True)),
                ('date_jugement', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bce', models.CharField(max_length=20, unique=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('json_source', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword1', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword2', models.CharField(blank=True, max_length=100, null=True)),
                ('keyword3', models.CharField(blank=True, max_length=100, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('TVA', 'Veille TVA'), ('KEYWORD', 'Veille Mots-clés')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_veille', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VeilleSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tva', models.CharField(max_length=20)),
                ('veille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societes', to='veille.veille')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionSociete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veille.decision')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veille.societe')),
            ],
            options={
                'unique_together': {('decision', 'societe')},
            },
        ),
        migrations.CreateModel(
            name='SocieteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veille.administrateur')),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veille.societe')),
            ],
            options={
                'unique_together': {('societe', 'admin')},
            },
        ),
        migrations.CreateModel(
            name='VeilleEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('source', models.URLField(max_length=500)),
                ('rubrique', models.CharField(blank=True, max_length=500, null=True)),
                ('titre', models.CharField(blank=True, max_length=500, null=True)),
                ('veille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='veille.veille')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veille.veillesociete')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('veille', 'societe', 'type', 'date_publication', 'source'), name='uniq_event_by_veille')],
            },
        ),
    ]
