# Generated by Django 5.2.4 on 2025-11-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veille', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='veillesociete',
            unique_together={('veille', 'numero_tva')},
        ),
    ]
